### PR TITLE
New version

### LINKED ISSUE #7: Hue of brown wool/stained glass is off
The hue of the brown wool/stained glass is kinda off. It does not look really brown.

And looking at it in the GIMP it's clear this is not just my imagination. Moving the saturation to max, it reveals it is actually more a red tone.

### PR DESCRIPTION
**Pull request by Wuzzy2**
I made a "few" updates. :D

* Many new buildings added
* Textures of blocks changed to be easier to distinguish (fixes #7, #5)
    * Logs improved
    * Stained glass is now actual glass rather than translucent wool
    * Confusing wool/glass colors fixed
    * Ore textures changed
    * Coal texture is now B/W (no purple)
    * Add lava animation
* Make lava glow
* Improve AFK detection (e.g. chat or punching are now detected as "on keyboard")
* Added a new type of sign (for the shop). It contains only a letter and is similar to a `signlike` node so building shop signs is now flexible; the "letter printed on a node" is gone
* Added "sign versions" of all blocks (also for the shop). These are the same as the building blocks, except with a little glow. These are used as shop signs.
* Bugfixes (fixes #2, #4, #6)
   * Fix crash on initial startup
   * Remove text on the top and bottom of the quartz blocks with text
   * The shop signs are now readable from both sides
   * Prevent buying when inventory is full
   * Update HUD immediately when money changes
   * Fix text flickering when pointing a building block or shop
   * Shop/block hover text now respects the hand pointing range
   * Fix a few schematic sizes

If this is too much for you, you can also check out the individual feature branches on my repo:

* `sounds`: Adds sounds
* `new_buildings`: Adds new buildings
* `bugfixes`: All bugfixes (includes the shop sign fix)
* `better_textures`: Node texture changes

Are you still interested in maintaining this? If not, I might release my own fork (not sure).

### CODE REVIEW

**Comment by Minetest-j45** [comment]
Hey there! Wow. I dont really know what else to say lmao. I really appreciate all the effort you have put in. I am currently on holidays but i will try and review all the code asap :). If you are interested in maintaining the project, i could give you commit access to this repo (as i am not particularly interested in investing lots of time, i might still help out every now and then)
It is up to you if you want to make your own fork or if u want commit access to this repo, just say :D

**Comment by Minetest-j45** [comment]
I have had a quick look at all the code and it all LGTM :)).
I cant view the textures or the sounds due to the GitHub android app being quite bad but im sure they are amazing!
I will wait for you to make your choice of if u want commit access or to make your own fork, before merging as i would feel bad if i merged this and then you wanted to fork (idk)

**Comment by Wuzzy2** [comment]
I should probably do a few explanations of a few commits.

8857d8b8a47f9f786392a5cba6f72c7fb16c91ed: The problem here is that if the building area was unloaded, the submission could be accepted via chat command. The reason this happened is because both the building and demo areas are all `ignore` nodes in the unloaded state, so they are seen as equal. The fix is thus to treat `ignore` as special, show an error and load the area.
* Shop signs: Already explained above, but for this I actually rebuilt the shop schematic as well
* fea8644d5332da250f04dbb61e73d5274185a62e: Previously, the HUD texts were just constantly added and removed, which caused the flickering. But the better approach is to just add the HUD element once but make it transparent. And use `hud_change` to update the text here. This is also better for server/client as it avoids package spam
* Sounds: All of these were created with the help of sfxr :-)

Feel free to ask more about why I did certain commits.

----

I'm not sure if I want to officially take over this project. I was basically just bored for 2-3 days, lol. Probably a proper fork is better as I have ideas to take this is a probably very different direction. Or maybe, if I am still interested in the idea, start something from scratch. But I don't know if I am still interested in large changes to this game in particular.

The biggest problem with this game now (even with this update) is the lack of actual gameplay and it just gets boring too fast. :-/

It is currently basically just sandbox mode with no goal, highscore or challenge although this type of game is *screaming* for this. Maybe you had similar ideas for a more arcade-style gameplay, but ran out of time.

Or maybe it's just the whole gameplay idea, i.e. "build and buy, but in singleplayer" simply just doesn't work out, no matter how hard you try, but I'm not sure about that yet.

Anyways, since I already did some stuff, I wanted to post it here to not go it to waste. :P

**Comment by Minetest-j45** [comment]
I understand why you wouldn't want to take over :)

Yea i totally agree, it does get quite boring, very fast.

The initial idea was for this to be a clone of BuildMart (from MCC, Minecraft Championship), which is multiplayer. Due to the limitations of time, i had to try make it work in single player (which didnt really work).

I will explain the main differences between this and BuildMart(BM), incase you are interested:
In BM, you are in teams of 3, and there are 3 "demos" to build, with one of these being worth significantly more points than the other 2. Which brings me to another difference, in BM, there are no coins, there is a score which you get from completing the demos. Instead of buying the blocks you need in BM, there are areas full of certain blocks (7\*7\*7 area if i had to estimate how large these are) and once the whole area has been mined, it gets automatically regenerated with the same blocks (for example, there is a stone block area where you go and mine the stone if you need it). In BM, there is a time limit, and after this time, the game ends and whichever team had the highest score wins(if we isolate this game from all the other MCC minigames)

Btw, i highly recommend watching some BuildMart gameplay as it is fun to watch! (You could either watch it in the next MCC if it comes up - i really like Grian's POV - or im sure you can find a VOD somewhere)

I think the idea of BM is a good one, but i executed it rather poorly and made some bad decisions in order to make BnB in time lol.


> Anyways, since I already did some stuff, I wanted to post it here to not go it to waste. :P

Nice, i will merge it now :), i think you should still be able to comment even after this pr is merged but if not, just open an issue or smt

**Pull request merged**
